language: python
python:
  - "3.6"  

services:
  - postgresql
before_script:
  - psql -c "create database challengethree_test;" -U postgres

install:
  - pip install -r requirements.txt

script:
  # - pytest -v --cov app --cov-report term-missing
  - pytest --cov

after_success:
  - coveralls

notifications:
  email: false